name: testing_downstream

on:
  # Run this workflow after the build workflow has completed.
  workflow_run:
    workflows: [build]
    types: [completed]
  workflow_dispatch:
    inputs:
      manual:
        description: don't change me!
        type: boolean
        required: true
        default: true

jobs:
  downstream_tests:
    uses: maximlt/run_downstream_tests/.github/workflows/run_downstream_tests.yaml@main
    with:
      downstream_repos_as_json: "{\"downstream_repo\":[\"downstream_1\", \"downstream_2\"]}"
    secrets:
      MY_PAT: ${{ secrets.MY_PAT }}
