name: testing_downstream

on: [push]

jobs:
  testing_downstream:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ['downstream_1', 'downstream_2']
      fail-fast: false
    steps:
    - uses: convictional/trigger-workflow-and-wait@v1.3.0
      with:
        owner: maximlt
        repo: ${{ matrix.repo }}
        github_token: ${{ secrets.MY_PAT }}
        workflow_file_name: test.yaml
        ref: main
        wait_interval: 10
        inputs: '{"mode": "from upstream"}'
        propagate_failure: false
        trigger_workflow: true
        wait_workflow: true
