name: downstream_test

on: [push]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.MY_PAT }}
        script: |
          const dummy = await github.rest.actions.createWorkflowDispatch({
            owner: 'maximlt',
            repo: 'test_a',
            workflow_id: 'test.yaml',
            ref: 'main',
            inputs: {"mode": "from another workflow"}
          })
          console.log(dummy)
