name: testing_downstream

on:
  # Run this workflow after the build workflow has completed.
  workflow_run:
    workflows: [build]
    types: [completed]

jobs:
  testing_downstream:
    runs-on: ubuntu-latest
    # Run only if the build workflow has completed with success.
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        repo: ['downstream_1', 'downstream_2']
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: "1"
    - name: Fetch tags
      run: git fetch --tags
    - name: Get version from git tag
      id: from_git
      run: |
        echo ::set-output name=version::${GITHUB_REF#refs/*/}
        echo "Got version ${GITHUB_REF#refs/*/} from git tag"
    - uses: conda-incubator/setup-miniconda@v2
      name: Install conda with miniconda
      with:
        miniconda-version: "latest"
        auto-activate-base: true
        activate-environment: ""
    - name: Get latest version available on conda
      shell: bash -l {0}
      run: |
        version=$(conda search -c pyviz/label/dev 'param=foo' --json | jq ".param[0].version")
        if [[ "$version" != "null" ]]
        then
          echo "Version ${{ steps.from_git.outputs.version }} found with conda search -c pyviz/dev/label"
        else
          echo "Version ${{ steps.from_git.outputs.version }} not found with conda search -c pyviz/dev/label"
          exit 1
        fi
    - uses: convictional/trigger-workflow-and-wait@v1.5.0
      name: Trigger downstream test workflow and wait
      with:
        owner: maximlt
        repo: ${{ matrix.repo }}
        github_token: ${{ secrets.MY_PAT }}
        workflow_file_name: test.yaml
        ref: main
        wait_interval: 10
        inputs: '{"caller": "from upstream"}'
        propagate_failure: true
        trigger_workflow: true
        wait_workflow: true


