name: testing_downstream

on:
  # Run this workflow after the build workflow has completed.
  workflow_run:
    workflows: [build]
    types: [completed]

jobs:
  testing_downstream:
    runs-on: ubuntu-latest
    # Run only if the build workflow has completed with success.
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        repo: ['downstream_1', 'downstream_2']
      fail-fast: false
    steps:
    - uses: convictional/trigger-workflow-and-wait@v1.5.0
      with:
        owner: maximlt
        repo: ${{ matrix.repo }}
        github_token: ${{ secrets.MY_PAT }}
        workflow_file_name: test.yaml
        ref: main
        wait_interval: 10
        inputs: '{"caller": "from upstream"}'
        propagate_failure: true
        trigger_workflow: true
        wait_workflow: true
